<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <ProjectReference Include="../../../modules/customers/Application.Customers.Postgres/Application.Customers.Postgres.csproj" />
    <ProjectReference Include="../../../modules/customers/Application.Customers/Application.Customers.csproj" />
    <PackageReference Include="Autofac" />
    <PackageReference Include="Autofac.Extensions.DependencyInjection" />
    <PackageReference Include="Finbuckle.MultiTenant.AspNetCore" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Npgsql" />
    <PackageReference Include="OpenFga.Sdk" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../../modules/branding/Application.Branding/Application.Branding.csproj" />
    <ProjectReference Include="../../../modules/identity-access/Application.IdentityAccess.Postgres/Application.IdentityAccess.Postgres.csproj" />
    <ProjectReference Include="../../../modules/identity-access/Application.IdentityAccess/Application.IdentityAccess.csproj" />
    <ProjectReference Include="../../../modules/orders/Application.Orders.Postgres/Application.Orders.Postgres.csproj" />
    <ProjectReference Include="../../../modules/orders/Application.Orders/Application.Orders.csproj" />
    <ProjectReference Include="../../../modules/tenancy/Application.Tenancy.Postgres/Application.Tenancy.Postgres.csproj" />
    <ProjectReference Include="../../../modules/tenancy/Application.Tenancy/Application.Tenancy.csproj" />
  </ItemGroup>
</Project>
