<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <ProjectReference Include="../../../foundation/application-kernel/SquiFlow.ApplicationKernel/SquiFlow.ApplicationKernel.csproj" />
    <ProjectReference Include="../../../modules/customers/SquiFlow.Customers/SquiFlow.Customers.csproj" />
  </ItemGroup>
</Project>
