<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <PackageReference Include="Autofac" />
    <PackageReference Include="Autofac.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../../modules/branding/SquiFlow.Branding/SquiFlow.Branding.csproj" />
    <ProjectReference Include="../../../modules/identity-access/SquiFlow.IdentityAccess.Postgres/SquiFlow.IdentityAccess.Postgres.csproj" />
    <ProjectReference Include="../../../modules/identity-access/SquiFlow.IdentityAccess/SquiFlow.IdentityAccess.csproj" />
    <ProjectReference Include="../../../modules/tenancy/SquiFlow.Tenancy.Postgres/SquiFlow.Tenancy.Postgres.csproj" />
    <ProjectReference Include="../../../modules/tenancy/SquiFlow.Tenancy/SquiFlow.Tenancy.csproj" />
  </ItemGroup>
</Project>
