// <auto-generated />
using System;
using Application.Customers.Postgres;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Application.Customers.Postgres.Migrations
{
    [DbContext(typeof(CustomerDbContext))]
    [Migration("20261006130446_CustomerDuplicatesAndImports")]
    partial class CustomerDuplicatesAndImports
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("customers")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Application.Customers.Postgres.CustomerAccountReferenceRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.HasKey("Id");

                    b.ToTable("accounts", "identity_access", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Application.Customers.Postgres.CustomerDuplicateCaseRow", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("case_id");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("Evidence")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("evidence");

                    b.Property<Guid>("OtherCustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("other_customer_id");

                    b.Property<int?>("Outcome")
                        .HasColumnType("integer")
                        .HasColumnName("outcome");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("reason");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<Guid?>("ResolvedByAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("resolved_by_account_id");

                    b.HasKey("TenantId", "CaseId")
                        .HasName("pk_customer_duplicate_cases");

                    b.HasIndex("ResolvedByAccountId");

                    b.HasIndex("TenantId", "OtherCustomerId");

                    b.HasIndex("TenantId", "CustomerId", "OtherCustomerId")
                        .HasDatabaseName("ix_customer_duplicate_cases_pair");

                    b.ToTable("duplicate_cases", "customers", t =>
                        {
                            t.HasCheckConstraint("ck_customer_duplicate_cases_outcome", "outcome IS NULL OR outcome IN (1, 2, 3, 4)");

                            t.HasCheckConstraint("ck_customer_duplicate_cases_pair", "customer_id <> other_customer_id");
                        });
                });

            modelBuilder.Entity("Application.Customers.Postgres.CustomerDuplicateReceiptRow", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<string>("Operation")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("operation");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("idempotency_key");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("fingerprint")
                        .IsFixedLength();

                    b.Property<Guid>("OtherCustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("other_customer_id");

                    b.Property<int>("Outcome")
                        .HasColumnType("integer")
                        .HasColumnName("outcome");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("reason");

                    b.Property<Guid>("ResolutionId")
                        .HasColumnType("uuid")
                        .HasColumnName("resolution_id");

                    b.Property<DateTimeOffset>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.HasKey("TenantId", "AccountId", "Operation", "IdempotencyKey")
                        .HasName("pk_customer_duplicate_command_receipts");

                    b.HasIndex("AccountId");

                    b.HasIndex("TenantId", "ResolutionId")
                        .HasDatabaseName("ix_customer_duplicate_receipts_resolution");

                    b.ToTable("duplicate_command_receipts", "customers", t =>
                        {
                            t.HasCheckConstraint("ck_customer_duplicate_receipts_fingerprint", "fingerprint ~ '^[0-9a-f]{64}$'");

                            t.HasCheckConstraint("ck_customer_duplicate_receipts_key", "btrim(idempotency_key) <> ''");

                            t.HasCheckConstraint("ck_customer_duplicate_receipts_operation", "operation IN ('resolve', 'consolidate')");

                            t.HasCheckConstraint("ck_customer_duplicate_receipts_outcome", "outcome IN (1, 2, 3, 4)");
                        });
                });

            modelBuilder.Entity("Application.Customers.Postgres.CustomerImportItemRow", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("ImportId")
                        .HasColumnType("uuid")
                        .HasColumnName("import_id");

                    b.Property<int>("RowNumber")
                        .HasColumnType("integer")
                        .HasColumnName("row_number");

                    b.Property<string>("AddressLine1")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("address_line1");

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("address_line2");

                    b.Property<string>("City")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("city");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("CustomerType")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("customer_type");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("error_code");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("error_message");

                    b.Property<string>("ExternalRegistrationId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("external_id");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("notes");

                    b.Property<string>("Phone")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("phone");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("SourceRowHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("source_row_hash")
                        .IsFixedLength();

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("TenantId", "ImportId", "RowNumber")
                        .HasName("pk_customer_import_rows");

                    b.HasIndex("TenantId", "CustomerId");

                    b.HasIndex("TenantId", "ImportId", "Status")
                        .HasDatabaseName("ix_customer_import_rows_status");

                    b.ToTable("import_rows", "customers", t =>
                        {
                            t.HasCheckConstraint("ck_customer_import_rows_hash", "source_row_hash ~ '^[0-9a-f]{64}$'");

                            t.HasCheckConstraint("ck_customer_import_rows_row", "row_number >= 2");

                            t.HasCheckConstraint("ck_customer_import_rows_status", "status IN (1, 2, 3, 4, 5)");
                        });
                });

            modelBuilder.Entity("Application.Customers.Postgres.CustomerImportRow", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("ImportId")
                        .HasColumnType("uuid")
                        .HasColumnName("import_id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<long>("ByteLength")
                        .HasColumnType("bigint")
                        .HasColumnName("byte_length");

                    b.Property<string>("ContractVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("contract_version");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_account_id");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("fingerprint")
                        .IsFixedLength();

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("ManifestHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("manifest_hash")
                        .IsFixedLength();

                    b.Property<int>("RowCount")
                        .HasColumnType("integer")
                        .HasColumnName("row_count");

                    b.HasKey("TenantId", "ImportId")
                        .HasName("pk_customer_imports");

                    b.HasIndex("AccountId");

                    b.HasIndex("CreatedByAccountId");

                    b.HasIndex("TenantId", "AccountId", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ux_customer_imports_operation");

                    b.HasIndex("TenantId", "ImportId", "Fingerprint")
                        .HasDatabaseName("ix_customer_imports_fingerprint");

                    b.ToTable("imports", "customers", t =>
                        {
                            t.HasCheckConstraint("ck_customer_imports_bytes", "byte_length BETWEEN 0 AND 10485760");

                            t.HasCheckConstraint("ck_customer_imports_contract", "contract_version = 'customer-import/v1'");

                            t.HasCheckConstraint("ck_customer_imports_hash", "manifest_hash ~ '^[0-9a-f]{64}$'");

                            t.HasCheckConstraint("ck_customer_imports_rows", "row_count BETWEEN 0 AND 10000");
                        });
                });

            modelBuilder.Entity("Application.Customers.Postgres.CustomerImportWorkRow", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("WorkId")
                        .HasColumnType("uuid")
                        .HasColumnName("work_id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("fingerprint")
                        .IsFixedLength();

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("idempotency_key");

                    b.Property<Guid>("ImportId")
                        .HasColumnType("uuid")
                        .HasColumnName("import_id");

                    b.Property<string>("LastError")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("last_error");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("TenantId", "WorkId")
                        .HasName("pk_customer_import_work");

                    b.HasIndex("AccountId");

                    b.HasIndex("TenantId", "ImportId");

                    b.HasIndex("TenantId", "AccountId", "ImportId", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ux_customer_import_work_operation");

                    b.ToTable("import_work", "customers", t =>
                        {
                            t.HasCheckConstraint("ck_customer_import_work_fingerprint", "fingerprint ~ '^[0-9a-f]{64}$'");

                            t.HasCheckConstraint("ck_customer_import_work_key", "btrim(idempotency_key) <> ''");

                            t.HasCheckConstraint("ck_customer_import_work_status", "status IN (1, 2, 3, 4)");
                        });
                });

            modelBuilder.Entity("Application.Customers.Postgres.CustomerIndividualCommandReceiptRow", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<string>("Operation")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("operation");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("idempotency_key");

                    b.Property<int>("Availability")
                        .HasColumnType("integer")
                        .HasColumnName("availability");

                    b.Property<DateTimeOffset?>("AvailabilityChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("availability_changed_at");

                    b.Property<Guid?>("AvailabilityChangedByAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("availability_changed_by_account_id");

                    b.Property<DateTimeOffset?>("ContactChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("contact_changed_at");

                    b.Property<Guid?>("ContactChangedByAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("contact_changed_by_account_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_account_id");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("fingerprint")
                        .IsFixedLength();

                    b.Property<Guid>("IndividualId")
                        .HasColumnType("uuid")
                        .HasColumnName("individual_id");

                    b.Property<string>("Phone")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("phone");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.HasKey("TenantId", "AccountId", "Operation", "IdempotencyKey")
                        .HasName("pk_customer_individual_command_receipts");

                    b.HasIndex("AccountId");

                    b.HasIndex("TenantId", "IndividualId")
                        .HasDatabaseName("ix_customer_individual_receipts_individual");

                    b.ToTable("individual_command_receipts", "customers", t =>
                        {
                            t.HasCheckConstraint("ck_customer_individual_receipts_availability", "availability IN (1, 2)");

                            t.HasCheckConstraint("ck_customer_individual_receipts_change_pair", "(availability_changed_by_account_id IS NULL) = (availability_changed_at IS NULL)");

                            t.HasCheckConstraint("ck_customer_individual_receipts_contact_change_pair", "(contact_changed_by_account_id IS NULL) = (contact_changed_at IS NULL)");

                            t.HasCheckConstraint("ck_customer_individual_receipts_customer_type", "btrim(customer_type) <> ''");

                            t.HasCheckConstraint("ck_customer_individual_receipts_fingerprint", "fingerprint ~ '^[0-9a-f]{64}$'");

                            t.HasCheckConstraint("ck_customer_individual_receipts_key", "btrim(idempotency_key) <> ''");

                            t.HasCheckConstraint("ck_customer_individual_receipts_name", "btrim(display_name) <> ''");

                            t.HasCheckConstraint("ck_customer_individual_receipts_operation", "operation IN ('create', 'availability', 'contact')");

                            t.HasCheckConstraint("ck_customer_individual_receipts_revision", "revision > 0");
                        });
                });

            modelBuilder.Entity("Application.Customers.Postgres.CustomerIndividualRow", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AddressLine1")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("address_line1");

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("address_line2");

                    b.Property<int>("Availability")
                        .HasColumnType("integer")
                        .HasColumnName("availability");

                    b.Property<DateTimeOffset?>("AvailabilityChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("availability_changed_at");

                    b.Property<Guid?>("AvailabilityChangedByAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("availability_changed_by_account_id");

                    b.Property<string>("City")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("city");

                    b.Property<DateTimeOffset?>("ContactChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("contact_changed_at");

                    b.Property<Guid?>("ContactChangedByAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("contact_changed_by_account_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_account_id");

                    b.Property<string>("CustomerType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("customer_type");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<string>("ExternalRegistrationId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("external_registration_id");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedExternalRegistrationId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("normalized_external_registration_id");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("normalized_name");

                    b.Property<string>("NormalizedPhone")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("normalized_phone");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("notes");

                    b.Property<string>("Phone")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("phone");

                    b.Property<Guid?>("RedirectTargetIndividualId")
                        .HasColumnType("uuid")
                        .HasColumnName("redirect_target_individual_id");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.HasKey("TenantId", "Id")
                        .HasName("pk_customer_individuals");

                    b.HasIndex("AvailabilityChangedByAccountId");

                    b.HasIndex("ContactChangedByAccountId");

                    b.HasIndex("CreatedByAccountId");

                    b.HasIndex("Id")
                        .IsUnique()
                        .HasDatabaseName("ux_customer_individuals_id");

                    b.HasIndex("TenantId", "NormalizedEmail")
                        .HasDatabaseName("ix_customer_individuals_normalized_email");

                    b.HasIndex("TenantId", "NormalizedExternalRegistrationId")
                        .HasDatabaseName("ix_customer_individuals_normalized_external_id");

                    b.HasIndex("TenantId", "NormalizedName")
                        .HasDatabaseName("ix_customer_individuals_normalized_name");

                    b.HasIndex("TenantId", "NormalizedPhone")
                        .HasDatabaseName("ix_customer_individuals_normalized_phone");

                    b.HasIndex("TenantId", "RedirectTargetIndividualId");

                    b.ToTable("individuals", "customers", t =>
                        {
                            t.HasCheckConstraint("ck_customer_individuals_availability", "availability IN (1, 2)");

                            t.HasCheckConstraint("ck_customer_individuals_change_pair", "(availability_changed_by_account_id IS NULL) = (availability_changed_at IS NULL)");

                            t.HasCheckConstraint("ck_customer_individuals_contact_change_pair", "(contact_changed_by_account_id IS NULL) = (contact_changed_at IS NULL)");

                            t.HasCheckConstraint("ck_customer_individuals_customer_type", "btrim(customer_type) <> ''");

                            t.HasCheckConstraint("ck_customer_individuals_email", "email IS NULL OR btrim(email) <> ''");

                            t.HasCheckConstraint("ck_customer_individuals_name", "btrim(display_name) <> ''");

                            t.HasCheckConstraint("ck_customer_individuals_phone", "phone IS NULL OR btrim(phone) <> ''");

                            t.HasCheckConstraint("ck_customer_individuals_redirect", "redirect_target_individual_id IS NULL OR redirect_target_individual_id <> id");

                            t.HasCheckConstraint("ck_customer_individuals_revision", "revision > 0");
                        });
                });

            modelBuilder.Entity("Application.Customers.Postgres.CustomerOrganizationRow", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_account_id");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.HasKey("TenantId", "Id")
                        .HasName("pk_customer_organizations");

                    b.HasIndex("CreatedByAccountId");

                    b.HasIndex("Id")
                        .IsUnique()
                        .HasDatabaseName("ux_customer_organizations_id");

                    b.HasIndex("TenantId", "CreatedAt", "Id")
                        .IsDescending(false, true, true)
                        .HasDatabaseName("ix_customer_organizations_browse");

                    b.ToTable("organizations", "customers", t =>
                        {
                            t.HasCheckConstraint("ck_customer_organizations_name", "btrim(display_name) <> ''");
                        });
                });

            modelBuilder.Entity("Application.Customers.Postgres.CustomerProgramRow", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_account_id");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.HasKey("TenantId", "Id")
                        .HasName("pk_customer_programs");

                    b.HasIndex("CreatedByAccountId");

                    b.HasIndex("Id")
                        .IsUnique()
                        .HasDatabaseName("ux_customer_programs_id");

                    b.HasIndex("TenantId", "OrganizationId", "Id")
                        .IsUnique()
                        .HasDatabaseName("ux_customer_programs_organization_identity");

                    b.HasIndex("TenantId", "OrganizationId", "CreatedAt", "Id")
                        .IsDescending(false, false, true, true)
                        .HasDatabaseName("ix_customer_programs_browse");

                    b.ToTable("programs", "customers", t =>
                        {
                            t.HasCheckConstraint("ck_customer_programs_name", "btrim(display_name) <> ''");
                        });
                });

            modelBuilder.Entity("Application.Customers.Postgres.CustomerRedirectRow", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("SourceCustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_customer_id");

                    b.Property<Guid>("CanonicalCustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("canonical_customer_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_account_id");

                    b.HasKey("TenantId", "SourceCustomerId")
                        .HasName("pk_customer_redirects");

                    b.HasIndex("CreatedByAccountId");

                    b.HasIndex("TenantId", "CanonicalCustomerId")
                        .HasDatabaseName("ix_customer_redirects_canonical");

                    b.ToTable("customer_redirects", "customers", t =>
                        {
                            t.HasCheckConstraint("ck_customer_redirects_pair", "source_customer_id <> canonical_customer_id");
                        });
                });

            modelBuilder.Entity("Application.Customers.Postgres.CustomerRepresentativeCommandReceiptRow", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<string>("Operation")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("operation");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("idempotency_key");

                    b.Property<int>("Availability")
                        .HasColumnType("integer")
                        .HasColumnName("availability");

                    b.Property<DateTimeOffset?>("ChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at");

                    b.Property<Guid?>("ChangedByAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("changed_by_account_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_account_id");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("fingerprint")
                        .IsFixedLength();

                    b.Property<Guid>("IndividualId")
                        .HasColumnType("uuid")
                        .HasColumnName("individual_id");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid?>("ProgramId")
                        .HasColumnType("uuid")
                        .HasColumnName("program_id");

                    b.Property<Guid>("RepresentativeId")
                        .HasColumnType("uuid")
                        .HasColumnName("representative_id");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.HasKey("TenantId", "AccountId", "Operation", "IdempotencyKey")
                        .HasName("pk_customer_representative_command_receipts");

                    b.HasIndex("AccountId");

                    b.HasIndex("TenantId", "RepresentativeId")
                        .HasDatabaseName("ix_customer_representative_receipts_representative");

                    b.ToTable("representative_command_receipts", "customers", t =>
                        {
                            t.HasCheckConstraint("ck_customer_representative_receipts_availability", "availability IN (1, 2)");

                            t.HasCheckConstraint("ck_customer_representative_receipts_change_pair", "(changed_by_account_id IS NULL) = (changed_at IS NULL)");

                            t.HasCheckConstraint("ck_customer_representative_receipts_fingerprint", "fingerprint ~ '^[0-9a-f]{64}$'");

                            t.HasCheckConstraint("ck_customer_representative_receipts_key", "btrim(idempotency_key) <> ''");

                            t.HasCheckConstraint("ck_customer_representative_receipts_operation", "operation IN ('link', 'unlink')");

                            t.HasCheckConstraint("ck_customer_representative_receipts_revision", "revision > 0");
                        });
                });

            modelBuilder.Entity("Application.Customers.Postgres.CustomerRepresentativeRow", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Availability")
                        .HasColumnType("integer")
                        .HasColumnName("availability");

                    b.Property<DateTimeOffset?>("ChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at");

                    b.Property<Guid?>("ChangedByAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("changed_by_account_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_account_id");

                    b.Property<Guid>("IndividualId")
                        .HasColumnType("uuid")
                        .HasColumnName("individual_id");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid?>("ProgramId")
                        .HasColumnType("uuid")
                        .HasColumnName("program_id");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.HasKey("TenantId", "Id")
                        .HasName("pk_customer_representatives");

                    b.HasIndex("ChangedByAccountId");

                    b.HasIndex("CreatedByAccountId");

                    b.HasIndex("Id")
                        .IsUnique()
                        .HasDatabaseName("ux_customer_representatives_id");

                    b.HasIndex("TenantId", "IndividualId");

                    b.HasIndex("TenantId", "ProgramId");

                    b.HasIndex("TenantId", "OrganizationId", "IndividualId")
                        .IsUnique()
                        .HasDatabaseName("ux_customer_representatives_active_organization")
                        .HasFilter("availability = 1 AND program_id IS NULL");

                    b.HasIndex("TenantId", "OrganizationId", "ProgramId", "IndividualId")
                        .IsUnique()
                        .HasDatabaseName("ux_customer_representatives_active_program")
                        .HasFilter("availability = 1 AND program_id IS NOT NULL");

                    b.ToTable("representatives", "customers", t =>
                        {
                            t.HasCheckConstraint("ck_customer_representatives_availability", "availability IN (1, 2)");

                            t.HasCheckConstraint("ck_customer_representatives_change_pair", "(changed_by_account_id IS NULL) = (changed_at IS NULL)");

                            t.HasCheckConstraint("ck_customer_representatives_revision", "revision > 0");
                        });
                });

            modelBuilder.Entity("Application.Customers.Postgres.CustomerTenantReferenceRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.HasKey("Id");

                    b.ToTable("tenants", "tenancy", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Application.Customers.Postgres.OrganizationReceiptRow", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("idempotency_key");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("fingerprint")
                        .IsFixedLength();

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.HasKey("TenantId", "AccountId", "IdempotencyKey")
                        .HasName("pk_customer_organization_receipts");

                    b.HasIndex("AccountId");

                    b.HasIndex("TenantId", "OrganizationId")
                        .HasDatabaseName("ix_customer_organization_receipts_organization");

                    b.ToTable("organization_receipts", "customers", t =>
                        {
                            t.HasCheckConstraint("ck_customer_organization_receipts_fingerprint", "fingerprint ~ '^[0-9a-f]{64}$'");

                            t.HasCheckConstraint("ck_customer_organization_receipts_key", "btrim(idempotency_key) <> ''");
                        });
                });

            modelBuilder.Entity("Application.Customers.Postgres.ProgramReceiptRow", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("idempotency_key");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("fingerprint")
                        .IsFixedLength();

                    b.Property<Guid>("ProgramId")
                        .HasColumnType("uuid")
                        .HasColumnName("program_id");

                    b.HasKey("TenantId", "AccountId", "IdempotencyKey")
                        .HasName("pk_customer_program_receipts");

                    b.HasIndex("AccountId");

                    b.HasIndex("TenantId", "ProgramId")
                        .HasDatabaseName("ix_customer_program_receipts_program");

                    b.ToTable("program_receipts", "customers", t =>
                        {
                            t.HasCheckConstraint("ck_customer_program_receipts_fingerprint", "fingerprint ~ '^[0-9a-f]{64}$'");

                            t.HasCheckConstraint("ck_customer_program_receipts_key", "btrim(idempotency_key) <> ''");
                        });
                });

            modelBuilder.Entity("Application.Customers.Postgres.CustomerDuplicateCaseRow", b =>
                {
                    b.HasOne("Application.Customers.Postgres.CustomerAccountReferenceRow", null)
                        .WithMany()
                        .HasForeignKey("ResolvedByAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("duplicate_cases_resolved_by_account_id_fkey");

                    b.HasOne("Application.Customers.Postgres.CustomerIndividualRow", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_customer_duplicate_cases_customer");

                    b.HasOne("Application.Customers.Postgres.CustomerIndividualRow", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "OtherCustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_customer_duplicate_cases_other_customer");
                });

            modelBuilder.Entity("Application.Customers.Postgres.CustomerDuplicateReceiptRow", b =>
                {
                    b.HasOne("Application.Customers.Postgres.CustomerAccountReferenceRow", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("duplicate_receipts_account_id_fkey");
                });

            modelBuilder.Entity("Application.Customers.Postgres.CustomerImportItemRow", b =>
                {
                    b.HasOne("Application.Customers.Postgres.CustomerIndividualRow", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_customer_import_rows_customer");

                    b.HasOne("Application.Customers.Postgres.CustomerImportRow", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ImportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_customer_import_rows_import");
                });

            modelBuilder.Entity("Application.Customers.Postgres.CustomerImportRow", b =>
                {
                    b.HasOne("Application.Customers.Postgres.CustomerAccountReferenceRow", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("imports_account_id_fkey");

                    b.HasOne("Application.Customers.Postgres.CustomerAccountReferenceRow", null)
                        .WithMany()
                        .HasForeignKey("CreatedByAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("imports_created_by_account_id_fkey");
                });

            modelBuilder.Entity("Application.Customers.Postgres.CustomerImportWorkRow", b =>
                {
                    b.HasOne("Application.Customers.Postgres.CustomerAccountReferenceRow", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("import_work_account_id_fkey");

                    b.HasOne("Application.Customers.Postgres.CustomerImportRow", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ImportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_customer_import_work_import");
                });

            modelBuilder.Entity("Application.Customers.Postgres.CustomerIndividualCommandReceiptRow", b =>
                {
                    b.HasOne("Application.Customers.Postgres.CustomerAccountReferenceRow", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("individual_receipts_account_id_fkey");

                    b.HasOne("Application.Customers.Postgres.CustomerIndividualRow", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "IndividualId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_customer_individual_receipts_individual");
                });

            modelBuilder.Entity("Application.Customers.Postgres.CustomerIndividualRow", b =>
                {
                    b.HasOne("Application.Customers.Postgres.CustomerAccountReferenceRow", null)
                        .WithMany()
                        .HasForeignKey("AvailabilityChangedByAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("individuals_availability_changed_by_account_id_fkey");

                    b.HasOne("Application.Customers.Postgres.CustomerAccountReferenceRow", null)
                        .WithMany()
                        .HasForeignKey("ContactChangedByAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("individuals_contact_changed_by_account_id_fkey");

                    b.HasOne("Application.Customers.Postgres.CustomerAccountReferenceRow", null)
                        .WithMany()
                        .HasForeignKey("CreatedByAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("individuals_created_by_account_id_fkey");

                    b.HasOne("Application.Customers.Postgres.CustomerTenantReferenceRow", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("individuals_tenant_id_fkey");

                    b.HasOne("Application.Customers.Postgres.CustomerIndividualRow", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "RedirectTargetIndividualId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_customer_individuals_redirect");
                });

            modelBuilder.Entity("Application.Customers.Postgres.CustomerOrganizationRow", b =>
                {
                    b.HasOne("Application.Customers.Postgres.CustomerAccountReferenceRow", null)
                        .WithMany()
                        .HasForeignKey("CreatedByAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("organizations_created_by_account_id_fkey");

                    b.HasOne("Application.Customers.Postgres.CustomerTenantReferenceRow", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("organizations_tenant_id_fkey");
                });

            modelBuilder.Entity("Application.Customers.Postgres.CustomerProgramRow", b =>
                {
                    b.HasOne("Application.Customers.Postgres.CustomerAccountReferenceRow", null)
                        .WithMany()
                        .HasForeignKey("CreatedByAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("programs_created_by_account_id_fkey");

                    b.HasOne("Application.Customers.Postgres.CustomerOrganizationRow", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_customer_programs_organization");
                });

            modelBuilder.Entity("Application.Customers.Postgres.CustomerRedirectRow", b =>
                {
                    b.HasOne("Application.Customers.Postgres.CustomerAccountReferenceRow", null)
                        .WithMany()
                        .HasForeignKey("CreatedByAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("redirects_created_by_account_id_fkey");

                    b.HasOne("Application.Customers.Postgres.CustomerIndividualRow", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CanonicalCustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_customer_redirects_canonical");

                    b.HasOne("Application.Customers.Postgres.CustomerIndividualRow", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "SourceCustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_customer_redirects_source");
                });

            modelBuilder.Entity("Application.Customers.Postgres.CustomerRepresentativeCommandReceiptRow", b =>
                {
                    b.HasOne("Application.Customers.Postgres.CustomerAccountReferenceRow", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("representative_receipts_account_id_fkey");

                    b.HasOne("Application.Customers.Postgres.CustomerRepresentativeRow", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "RepresentativeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_customer_representative_receipts_representative");
                });

            modelBuilder.Entity("Application.Customers.Postgres.CustomerRepresentativeRow", b =>
                {
                    b.HasOne("Application.Customers.Postgres.CustomerAccountReferenceRow", null)
                        .WithMany()
                        .HasForeignKey("ChangedByAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("representatives_changed_by_account_id_fkey");

                    b.HasOne("Application.Customers.Postgres.CustomerAccountReferenceRow", null)
                        .WithMany()
                        .HasForeignKey("CreatedByAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("representatives_created_by_account_id_fkey");

                    b.HasOne("Application.Customers.Postgres.CustomerIndividualRow", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "IndividualId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_customer_representatives_individual");

                    b.HasOne("Application.Customers.Postgres.CustomerOrganizationRow", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_customer_representatives_organization");

                    b.HasOne("Application.Customers.Postgres.CustomerProgramRow", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ProgramId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_customer_representatives_program");
                });

            modelBuilder.Entity("Application.Customers.Postgres.OrganizationReceiptRow", b =>
                {
                    b.HasOne("Application.Customers.Postgres.CustomerAccountReferenceRow", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("organization_receipts_account_id_fkey");

                    b.HasOne("Application.Customers.Postgres.CustomerOrganizationRow", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_customer_organization_receipts_organization");
                });

            modelBuilder.Entity("Application.Customers.Postgres.ProgramReceiptRow", b =>
                {
                    b.HasOne("Application.Customers.Postgres.CustomerAccountReferenceRow", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("program_receipts_account_id_fkey");

                    b.HasOne("Application.Customers.Postgres.CustomerProgramRow", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ProgramId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_customer_program_receipts_program");
                });
#pragma warning restore 612, 618
        }
    }
}
