using System;
// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Application.Customers.Postgres.Migrations;

/// <inheritdoc />
public partial class CustomerDuplicatesAndImports : Migration
{
    /// <inheritdoc />
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.AddColumn<string>(
            name: "address_line1",
            schema: "customers",
            table: "individuals",
            type: "character varying(200)",
            maxLength: 200,
            nullable: true);

        migrationBuilder.AddColumn<string>(
            name: "address_line2",
            schema: "customers",
            table: "individuals",
            type: "character varying(200)",
            maxLength: 200,
            nullable: true);

        migrationBuilder.AddColumn<string>(
            name: "city",
            schema: "customers",
            table: "individuals",
            type: "character varying(120)",
            maxLength: 120,
            nullable: true);

        migrationBuilder.AddColumn<string>(
            name: "customer_type",
            schema: "customers",
            table: "individuals",
            type: "character varying(32)",
            maxLength: 32,
            nullable: false,
             defaultValue: "individual");

        migrationBuilder.AddColumn<string>(
            name: "external_registration_id",
            schema: "customers",
            table: "individuals",
            type: "character varying(200)",
            maxLength: 200,
            nullable: true);

        migrationBuilder.AddColumn<string>(
            name: "normalized_email",
            schema: "customers",
            table: "individuals",
            type: "character varying(254)",
            maxLength: 254,
            nullable: true);

        migrationBuilder.AddColumn<string>(
            name: "normalized_external_registration_id",
            schema: "customers",
            table: "individuals",
            type: "character varying(200)",
            maxLength: 200,
            nullable: true);

        migrationBuilder.AddColumn<string>(
            name: "normalized_name",
            schema: "customers",
            table: "individuals",
            type: "character varying(200)",
            maxLength: 200,
            nullable: true);

        migrationBuilder.AddColumn<string>(
            name: "normalized_phone",
            schema: "customers",
            table: "individuals",
            type: "character varying(32)",
            maxLength: 32,
            nullable: true);

        migrationBuilder.AddColumn<string>(
            name: "notes",
            schema: "customers",
            table: "individuals",
            type: "character varying(4000)",
            maxLength: 4000,
            nullable: true);

        migrationBuilder.AddColumn<Guid>(
            name: "redirect_target_individual_id",
            schema: "customers",
            table: "individuals",
            type: "uuid",
            nullable: true);

        migrationBuilder.CreateTable(
            name: "customer_redirects",
            schema: "customers",
            columns: table => new
            {
                tenant_id = table.Column<Guid>(type: "uuid", nullable: false),
                source_customer_id = table.Column<Guid>(type: "uuid", nullable: false),
                canonical_customer_id = table.Column<Guid>(type: "uuid", nullable: false),
                created_by_account_id = table.Column<Guid>(type: "uuid", nullable: false),
                created_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false)
            },
            constraints: table =>
            {
                table.PrimaryKey("pk_customer_redirects", x => new { x.tenant_id, x.source_customer_id });
                table.CheckConstraint("ck_customer_redirects_pair", "source_customer_id <> canonical_customer_id");
                table.ForeignKey(
                    name: "fk_customer_redirects_canonical",
                    columns: x => new { x.tenant_id, x.canonical_customer_id },
                    principalSchema: "customers",
                    principalTable: "individuals",
                    principalColumns: new[] { "tenant_id", "id" },
                    onDelete: ReferentialAction.Restrict);
                table.ForeignKey(
                    name: "fk_customer_redirects_source",
                    columns: x => new { x.tenant_id, x.source_customer_id },
                    principalSchema: "customers",
                    principalTable: "individuals",
                    principalColumns: new[] { "tenant_id", "id" },
                    onDelete: ReferentialAction.Restrict);
                table.ForeignKey(
                    name: "redirects_created_by_account_id_fkey",
                    column: x => x.created_by_account_id,
                    principalSchema: "identity_access",
                    principalTable: "accounts",
                    principalColumn: "id",
                    onDelete: ReferentialAction.Restrict);
            });

        migrationBuilder.CreateTable(
            name: "duplicate_cases",
            schema: "customers",
            columns: table => new
            {
                tenant_id = table.Column<Guid>(type: "uuid", nullable: false),
                case_id = table.Column<Guid>(type: "uuid", nullable: false),
                customer_id = table.Column<Guid>(type: "uuid", nullable: false),
                other_customer_id = table.Column<Guid>(type: "uuid", nullable: false),
                evidence = table.Column<string>(type: "character varying(512)", maxLength: 512, nullable: false),
                outcome = table.Column<int>(type: "integer", nullable: true),
                resolved_by_account_id = table.Column<Guid>(type: "uuid", nullable: true),
                resolved_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                reason = table.Column<string>(type: "character varying(1000)", maxLength: 1000, nullable: true)
            },
            constraints: table =>
            {
                table.PrimaryKey("pk_customer_duplicate_cases", x => new { x.tenant_id, x.case_id });
                table.CheckConstraint("ck_customer_duplicate_cases_outcome", "outcome IS NULL OR outcome IN (1, 2, 3, 4)");
                table.CheckConstraint("ck_customer_duplicate_cases_pair", "customer_id <> other_customer_id");
                table.ForeignKey(
                    name: "duplicate_cases_resolved_by_account_id_fkey",
                    column: x => x.resolved_by_account_id,
                    principalSchema: "identity_access",
                    principalTable: "accounts",
                    principalColumn: "id",
                    onDelete: ReferentialAction.Restrict);
                table.ForeignKey(
                    name: "fk_customer_duplicate_cases_customer",
                    columns: x => new { x.tenant_id, x.customer_id },
                    principalSchema: "customers",
                    principalTable: "individuals",
                    principalColumns: new[] { "tenant_id", "id" },
                    onDelete: ReferentialAction.Restrict);
                table.ForeignKey(
                    name: "fk_customer_duplicate_cases_other_customer",
                    columns: x => new { x.tenant_id, x.other_customer_id },
                    principalSchema: "customers",
                    principalTable: "individuals",
                    principalColumns: new[] { "tenant_id", "id" },
                    onDelete: ReferentialAction.Restrict);
            });

        migrationBuilder.CreateTable(
            name: "duplicate_command_receipts",
            schema: "customers",
            columns: table => new
            {
                tenant_id = table.Column<Guid>(type: "uuid", nullable: false),
                account_id = table.Column<Guid>(type: "uuid", nullable: false),
                operation = table.Column<string>(type: "character varying(16)", maxLength: 16, nullable: false),
                idempotency_key = table.Column<string>(type: "character varying(128)", maxLength: 128, nullable: false),
                fingerprint = table.Column<string>(type: "character(64)", fixedLength: true, maxLength: 64, nullable: false),
                resolution_id = table.Column<Guid>(type: "uuid", nullable: false),
                customer_id = table.Column<Guid>(type: "uuid", nullable: false),
                other_customer_id = table.Column<Guid>(type: "uuid", nullable: false),
                outcome = table.Column<int>(type: "integer", nullable: false),
                resolved_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
                reason = table.Column<string>(type: "character varying(1000)", maxLength: 1000, nullable: true)
            },
            constraints: table =>
            {
                table.PrimaryKey("pk_customer_duplicate_command_receipts", x => new { x.tenant_id, x.account_id, x.operation, x.idempotency_key });
                table.CheckConstraint("ck_customer_duplicate_receipts_fingerprint", "fingerprint ~ '^[0-9a-f]{64}$'");
                table.CheckConstraint("ck_customer_duplicate_receipts_key", "btrim(idempotency_key) <> ''");
                table.CheckConstraint("ck_customer_duplicate_receipts_operation", "operation IN ('resolve', 'consolidate')");
                table.CheckConstraint("ck_customer_duplicate_receipts_outcome", "outcome IN (1, 2, 3, 4)");
                table.ForeignKey(
                    name: "duplicate_receipts_account_id_fkey",
                    column: x => x.account_id,
                    principalSchema: "identity_access",
                    principalTable: "accounts",
                    principalColumn: "id",
                    onDelete: ReferentialAction.Restrict);
            });

        migrationBuilder.CreateTable(
            name: "imports",
            schema: "customers",
            columns: table => new
            {
                tenant_id = table.Column<Guid>(type: "uuid", nullable: false),
                import_id = table.Column<Guid>(type: "uuid", nullable: false),
                account_id = table.Column<Guid>(type: "uuid", nullable: false),
                idempotency_key = table.Column<string>(type: "character varying(128)", maxLength: 128, nullable: false),
                fingerprint = table.Column<string>(type: "character(64)", fixedLength: true, maxLength: 64, nullable: false),
                created_by_account_id = table.Column<Guid>(type: "uuid", nullable: false),
                contract_version = table.Column<string>(type: "character varying(32)", maxLength: 32, nullable: false),
                manifest_hash = table.Column<string>(type: "character(64)", fixedLength: true, maxLength: 64, nullable: false),
                byte_length = table.Column<long>(type: "bigint", nullable: false),
                row_count = table.Column<int>(type: "integer", nullable: false),
                created_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false)
            },
            constraints: table =>
            {
                table.PrimaryKey("pk_customer_imports", x => new { x.tenant_id, x.import_id });
                table.CheckConstraint("ck_customer_imports_bytes", "byte_length BETWEEN 0 AND 10485760");
                table.CheckConstraint("ck_customer_imports_contract", "contract_version = 'customer-import/v1'");
                table.CheckConstraint("ck_customer_imports_hash", "manifest_hash ~ '^[0-9a-f]{64}$'");
                table.CheckConstraint("ck_customer_imports_rows", "row_count BETWEEN 0 AND 10000");
                table.ForeignKey(
                    name: "imports_account_id_fkey",
                    column: x => x.account_id,
                    principalSchema: "identity_access",
                    principalTable: "accounts",
                    principalColumn: "id",
                    onDelete: ReferentialAction.Restrict);
                table.ForeignKey(
                    name: "imports_created_by_account_id_fkey",
                    column: x => x.created_by_account_id,
                    principalSchema: "identity_access",
                    principalTable: "accounts",
                    principalColumn: "id",
                    onDelete: ReferentialAction.Restrict);
            });

        migrationBuilder.CreateTable(
            name: "import_rows",
            schema: "customers",
            columns: table => new
            {
                tenant_id = table.Column<Guid>(type: "uuid", nullable: false),
                import_id = table.Column<Guid>(type: "uuid", nullable: false),
                row_number = table.Column<int>(type: "integer", nullable: false),
                source_row_hash = table.Column<string>(type: "character(64)", fixedLength: true, maxLength: 64, nullable: false),
                name = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: true),
                customer_type = table.Column<string>(type: "character varying(32)", maxLength: 32, nullable: true),
                external_id = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: true),
                email = table.Column<string>(type: "character varying(254)", maxLength: 254, nullable: true),
                phone = table.Column<string>(type: "character varying(32)", maxLength: 32, nullable: true),
                address_line1 = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: true),
                address_line2 = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: true),
                city = table.Column<string>(type: "character varying(120)", maxLength: 120, nullable: true),
                notes = table.Column<string>(type: "character varying(4000)", maxLength: 4000, nullable: true),
                status = table.Column<int>(type: "integer", nullable: false),
                error_code = table.Column<string>(type: "character varying(64)", maxLength: 64, nullable: true),
                error_message = table.Column<string>(type: "character varying(1000)", maxLength: 1000, nullable: true),
                customer_id = table.Column<Guid>(type: "uuid", nullable: true),
                processed_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true)
            },
            constraints: table =>
            {
                table.PrimaryKey("pk_customer_import_rows", x => new { x.tenant_id, x.import_id, x.row_number });
                table.CheckConstraint("ck_customer_import_rows_hash", "source_row_hash ~ '^[0-9a-f]{64}$'");
                table.CheckConstraint("ck_customer_import_rows_row", "row_number >= 2");
                table.CheckConstraint("ck_customer_import_rows_status", "status IN (1, 2, 3, 4, 5)");
                table.ForeignKey(
                    name: "fk_customer_import_rows_customer",
                    columns: x => new { x.tenant_id, x.customer_id },
                    principalSchema: "customers",
                    principalTable: "individuals",
                    principalColumns: new[] { "tenant_id", "id" },
                    onDelete: ReferentialAction.Restrict);
                table.ForeignKey(
                    name: "fk_customer_import_rows_import",
                    columns: x => new { x.tenant_id, x.import_id },
                    principalSchema: "customers",
                    principalTable: "imports",
                    principalColumns: new[] { "tenant_id", "import_id" },
                    onDelete: ReferentialAction.Restrict);
            });

        migrationBuilder.CreateTable(
            name: "import_work",
            schema: "customers",
            columns: table => new
            {
                tenant_id = table.Column<Guid>(type: "uuid", nullable: false),
                work_id = table.Column<Guid>(type: "uuid", nullable: false),
                import_id = table.Column<Guid>(type: "uuid", nullable: false),
                account_id = table.Column<Guid>(type: "uuid", nullable: false),
                idempotency_key = table.Column<string>(type: "character varying(128)", maxLength: 128, nullable: false),
                fingerprint = table.Column<string>(type: "character(64)", fixedLength: true, maxLength: 64, nullable: false),
                status = table.Column<int>(type: "integer", nullable: false),
                created_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
                completed_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                last_error = table.Column<string>(type: "character varying(1000)", maxLength: 1000, nullable: true)
            },
            constraints: table =>
            {
                table.PrimaryKey("pk_customer_import_work", x => new { x.tenant_id, x.work_id });
                table.CheckConstraint("ck_customer_import_work_fingerprint", "fingerprint ~ '^[0-9a-f]{64}$'");
                table.CheckConstraint("ck_customer_import_work_key", "btrim(idempotency_key) <> ''");
                table.CheckConstraint("ck_customer_import_work_status", "status IN (1, 2, 3, 4)");
                table.ForeignKey(
                    name: "fk_customer_import_work_import",
                    columns: x => new { x.tenant_id, x.import_id },
                    principalSchema: "customers",
                    principalTable: "imports",
                    principalColumns: new[] { "tenant_id", "import_id" },
                    onDelete: ReferentialAction.Restrict);
                table.ForeignKey(
                    name: "import_work_account_id_fkey",
                    column: x => x.account_id,
                    principalSchema: "identity_access",
                    principalTable: "accounts",
                    principalColumn: "id",
                    onDelete: ReferentialAction.Restrict);
            });

        migrationBuilder.CreateIndex(
            name: "ix_customer_individuals_normalized_email",
            schema: "customers",
            table: "individuals",
            columns: new[] { "tenant_id", "normalized_email" });

        migrationBuilder.CreateIndex(
            name: "ix_customer_individuals_normalized_external_id",
            schema: "customers",
            table: "individuals",
            columns: new[] { "tenant_id", "normalized_external_registration_id" });

        migrationBuilder.CreateIndex(
            name: "ix_customer_individuals_normalized_name",
            schema: "customers",
            table: "individuals",
            columns: new[] { "tenant_id", "normalized_name" });

        migrationBuilder.CreateIndex(
            name: "ix_customer_individuals_normalized_phone",
            schema: "customers",
            table: "individuals",
            columns: new[] { "tenant_id", "normalized_phone" });

        migrationBuilder.CreateIndex(
            name: "IX_individuals_tenant_id_redirect_target_individual_id",
            schema: "customers",
            table: "individuals",
            columns: new[] { "tenant_id", "redirect_target_individual_id" });

        migrationBuilder.AddCheckConstraint(
            name: "ck_customer_individuals_customer_type",
            schema: "customers",
            table: "individuals",
            sql: "btrim(customer_type) <> ''");

        migrationBuilder.AddCheckConstraint(
            name: "ck_customer_individuals_redirect",
            schema: "customers",
            table: "individuals",
            sql: "redirect_target_individual_id IS NULL OR redirect_target_individual_id <> id");

        migrationBuilder.CreateIndex(
            name: "ix_customer_redirects_canonical",
            schema: "customers",
            table: "customer_redirects",
            columns: new[] { "tenant_id", "canonical_customer_id" });

        migrationBuilder.CreateIndex(
            name: "IX_customer_redirects_created_by_account_id",
            schema: "customers",
            table: "customer_redirects",
            column: "created_by_account_id");

        migrationBuilder.CreateIndex(
            name: "ix_customer_duplicate_cases_pair",
            schema: "customers",
            table: "duplicate_cases",
            columns: new[] { "tenant_id", "customer_id", "other_customer_id" });

        migrationBuilder.CreateIndex(
            name: "IX_duplicate_cases_resolved_by_account_id",
            schema: "customers",
            table: "duplicate_cases",
            column: "resolved_by_account_id");

        migrationBuilder.CreateIndex(
            name: "IX_duplicate_cases_tenant_id_other_customer_id",
            schema: "customers",
            table: "duplicate_cases",
            columns: new[] { "tenant_id", "other_customer_id" });

        migrationBuilder.CreateIndex(
            name: "ix_customer_duplicate_receipts_resolution",
            schema: "customers",
            table: "duplicate_command_receipts",
            columns: new[] { "tenant_id", "resolution_id" });

        migrationBuilder.CreateIndex(
            name: "IX_duplicate_command_receipts_account_id",
            schema: "customers",
            table: "duplicate_command_receipts",
            column: "account_id");

        migrationBuilder.CreateIndex(
            name: "ix_customer_import_rows_status",
            schema: "customers",
            table: "import_rows",
            columns: new[] { "tenant_id", "import_id", "status" });

        migrationBuilder.CreateIndex(
            name: "IX_import_rows_tenant_id_customer_id",
            schema: "customers",
            table: "import_rows",
            columns: new[] { "tenant_id", "customer_id" });

        migrationBuilder.CreateIndex(
            name: "IX_import_work_account_id",
            schema: "customers",
            table: "import_work",
            column: "account_id");

        migrationBuilder.CreateIndex(
            name: "IX_import_work_tenant_id_import_id",
            schema: "customers",
            table: "import_work",
            columns: new[] { "tenant_id", "import_id" });

        migrationBuilder.CreateIndex(
            name: "ux_customer_import_work_operation",
            schema: "customers",
            table: "import_work",
            columns: new[] { "tenant_id", "account_id", "import_id", "idempotency_key" },
            unique: true);

        migrationBuilder.CreateIndex(
            name: "ix_customer_imports_fingerprint",
            schema: "customers",
            table: "imports",
            columns: new[] { "tenant_id", "import_id", "fingerprint" });

        migrationBuilder.CreateIndex(
            name: "IX_imports_account_id",
            schema: "customers",
            table: "imports",
            column: "account_id");

        migrationBuilder.CreateIndex(
            name: "IX_imports_created_by_account_id",
            schema: "customers",
            table: "imports",
            column: "created_by_account_id");

        migrationBuilder.CreateIndex(
            name: "ux_customer_imports_operation",
            schema: "customers",
            table: "imports",
            columns: new[] { "tenant_id", "account_id", "idempotency_key" },
            unique: true);

        migrationBuilder.AddForeignKey(
            name: "fk_customer_individuals_redirect",
            schema: "customers",
            table: "individuals",
            columns: new[] { "tenant_id", "redirect_target_individual_id" },
            principalSchema: "customers",
            principalTable: "individuals",
            principalColumns: new[] { "tenant_id", "id" },
            onDelete: ReferentialAction.Restrict);

        migrationBuilder.Sql("""
            UPDATE customers.individuals
            SET customer_type = CASE WHEN btrim(customer_type) = '' THEN 'individual' ELSE lower(btrim(customer_type)) END,
                normalized_name = upper(btrim(display_name)),
                normalized_email = CASE WHEN email IS NULL THEN NULL ELSE upper(btrim(email)) END,
                normalized_phone = CASE WHEN phone IS NULL THEN NULL ELSE regexp_replace(phone, '[^0-9]', '', 'g') END,
                normalized_external_registration_id = CASE WHEN external_registration_id IS NULL THEN NULL ELSE upper(btrim(external_registration_id)) END;
            ALTER TABLE customers.individuals ALTER COLUMN customer_type SET DEFAULT 'individual';
            """);

        foreach (var table in new[] { "customer_redirects", "duplicate_cases", "duplicate_command_receipts",
            "imports", "import_rows", "import_work" })
        {
            migrationBuilder.Sql($"""
                ALTER TABLE customers.{table} ENABLE ROW LEVEL SECURITY;
                ALTER TABLE customers.{table} FORCE ROW LEVEL SECURITY;
                CREATE POLICY {table}_tenant_isolation ON customers.{table}
                    USING (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid)
                    WITH CHECK (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);
                """);
        }
    }

    /// <inheritdoc />
    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql("""
            LOCK TABLE customers.customer_redirects,customers.duplicate_cases,customers.duplicate_command_receipts,
                customers.imports,customers.import_rows,customers.import_work IN ACCESS EXCLUSIVE MODE;
            DO $guard$ DECLARE tenant uuid; BEGIN
                FOR tenant IN SELECT id FROM tenancy.tenants LOOP
                    PERFORM set_config('app.current_tenant',tenant::text,true);
                    IF EXISTS(SELECT 1 FROM customers.customer_redirects WHERE tenant_id=tenant)
                      OR EXISTS(SELECT 1 FROM customers.duplicate_command_receipts WHERE tenant_id=tenant)
                      OR EXISTS(SELECT 1 FROM customers.imports WHERE tenant_id=tenant) THEN
                        RAISE EXCEPTION 'Cannot roll back while retained Customers duplicate/import evidence exists';
                    END IF;
                END LOOP;
            END $guard$;
            """);
        migrationBuilder.DropForeignKey(
            name: "fk_customer_individuals_redirect",
            schema: "customers",
            table: "individuals");

        migrationBuilder.DropTable(
            name: "customer_redirects",
            schema: "customers");

        migrationBuilder.DropTable(
            name: "duplicate_cases",
            schema: "customers");

        migrationBuilder.DropTable(
            name: "duplicate_command_receipts",
            schema: "customers");

        migrationBuilder.DropTable(
            name: "import_rows",
            schema: "customers");

        migrationBuilder.DropTable(
            name: "import_work",
            schema: "customers");

        migrationBuilder.DropTable(
            name: "imports",
            schema: "customers");

        migrationBuilder.DropIndex(
            name: "ix_customer_individuals_normalized_email",
            schema: "customers",
            table: "individuals");

        migrationBuilder.DropIndex(
            name: "ix_customer_individuals_normalized_external_id",
            schema: "customers",
            table: "individuals");

        migrationBuilder.DropIndex(
            name: "ix_customer_individuals_normalized_name",
            schema: "customers",
            table: "individuals");

        migrationBuilder.DropIndex(
            name: "ix_customer_individuals_normalized_phone",
            schema: "customers",
            table: "individuals");

        migrationBuilder.DropIndex(
            name: "IX_individuals_tenant_id_redirect_target_individual_id",
            schema: "customers",
            table: "individuals");

        migrationBuilder.DropCheckConstraint(
            name: "ck_customer_individuals_customer_type",
            schema: "customers",
            table: "individuals");

        migrationBuilder.DropCheckConstraint(
            name: "ck_customer_individuals_redirect",
            schema: "customers",
            table: "individuals");

        migrationBuilder.DropColumn(
            name: "address_line1",
            schema: "customers",
            table: "individuals");

        migrationBuilder.DropColumn(
            name: "address_line2",
            schema: "customers",
            table: "individuals");

        migrationBuilder.DropColumn(
            name: "city",
            schema: "customers",
            table: "individuals");

        migrationBuilder.DropColumn(
            name: "customer_type",
            schema: "customers",
            table: "individuals");

        migrationBuilder.DropColumn(
            name: "external_registration_id",
            schema: "customers",
            table: "individuals");

        migrationBuilder.DropColumn(
            name: "normalized_email",
            schema: "customers",
            table: "individuals");

        migrationBuilder.DropColumn(
            name: "normalized_external_registration_id",
            schema: "customers",
            table: "individuals");

        migrationBuilder.DropColumn(
            name: "normalized_name",
            schema: "customers",
            table: "individuals");

        migrationBuilder.DropColumn(
            name: "normalized_phone",
            schema: "customers",
            table: "individuals");

        migrationBuilder.DropColumn(
            name: "notes",
            schema: "customers",
            table: "individuals");

        migrationBuilder.DropColumn(
            name: "redirect_target_individual_id",
            schema: "customers",
            table: "individuals");
    }
}
