// <auto-generated />
using System;
using Application.Customers.Postgres;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Application.Customers.Postgres.Migrations
{
    [DbContext(typeof(CustomerDbContext))]
    [Migration("202610030001_CustomerIndividuals")]
    partial class CustomerIndividuals
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("customers")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Application.Customers.Postgres.CustomerAccountReferenceRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.HasKey("Id");

                    b.ToTable("accounts", "identity_access", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Application.Customers.Postgres.CustomerOrganizationRow", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_account_id");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.HasKey("TenantId", "Id")
                        .HasName("pk_customer_organizations");

                    b.HasIndex("CreatedByAccountId");

                    b.HasIndex("Id")
                        .IsUnique()
                        .HasDatabaseName("ux_customer_organizations_id");

                    b.HasIndex("TenantId", "CreatedAt", "Id")
                        .IsDescending(false, true, true)
                        .HasDatabaseName("ix_customer_organizations_browse");

                    b.ToTable("organizations", "customers", t =>
                        {
                            t.HasCheckConstraint("ck_customer_organizations_name", "btrim(display_name) <> ''");
                        });
                });

            modelBuilder.Entity("Application.Customers.Postgres.CustomerProgramRow", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_account_id");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.HasKey("TenantId", "Id")
                        .HasName("pk_customer_programs");

                    b.HasIndex("CreatedByAccountId");

                    b.HasIndex("Id")
                        .IsUnique()
                        .HasDatabaseName("ux_customer_programs_id");

                    b.HasIndex("TenantId", "OrganizationId", "Id")
                        .IsUnique()
                        .HasDatabaseName("ux_customer_programs_organization_identity");

                    b.HasIndex("TenantId", "OrganizationId", "CreatedAt", "Id")
                        .IsDescending(false, false, true, true)
                        .HasDatabaseName("ix_customer_programs_browse");

                    b.ToTable("programs", "customers", t =>
                        {
                            t.HasCheckConstraint("ck_customer_programs_name", "btrim(display_name) <> ''");
                        });
                });

            modelBuilder.Entity("Application.Customers.Postgres.CustomerTenantReferenceRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.HasKey("Id");

                    b.ToTable("tenants", "tenancy", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Application.Customers.Postgres.OrganizationReceiptRow", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("idempotency_key");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("fingerprint")
                        .IsFixedLength();

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.HasKey("TenantId", "AccountId", "IdempotencyKey")
                        .HasName("pk_customer_organization_receipts");

                    b.HasIndex("AccountId");

                    b.HasIndex("TenantId", "OrganizationId")
                        .HasDatabaseName("ix_customer_organization_receipts_organization");

                    b.ToTable("organization_receipts", "customers", t =>
                        {
                            t.HasCheckConstraint("ck_customer_organization_receipts_fingerprint", "fingerprint ~ '^[0-9a-f]{64}$'");

                            t.HasCheckConstraint("ck_customer_organization_receipts_key", "btrim(idempotency_key) <> ''");
                        });
                });

            modelBuilder.Entity("Application.Customers.Postgres.ProgramReceiptRow", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("idempotency_key");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("fingerprint")
                        .IsFixedLength();

                    b.Property<Guid>("ProgramId")
                        .HasColumnType("uuid")
                        .HasColumnName("program_id");

                    b.HasKey("TenantId", "AccountId", "IdempotencyKey")
                        .HasName("pk_customer_program_receipts");

                    b.HasIndex("AccountId");

                    b.HasIndex("TenantId", "ProgramId")
                        .HasDatabaseName("ix_customer_program_receipts_program");

                    b.ToTable("program_receipts", "customers", t =>
                        {
                            t.HasCheckConstraint("ck_customer_program_receipts_fingerprint", "fingerprint ~ '^[0-9a-f]{64}$'");

                            t.HasCheckConstraint("ck_customer_program_receipts_key", "btrim(idempotency_key) <> ''");
                        });
                });

            modelBuilder.Entity("Application.Customers.Postgres.CustomerOrganizationRow", b =>
                {
                    b.HasOne("Application.Customers.Postgres.CustomerAccountReferenceRow", null)
                        .WithMany()
                        .HasForeignKey("CreatedByAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("organizations_created_by_account_id_fkey");

                    b.HasOne("Application.Customers.Postgres.CustomerTenantReferenceRow", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("organizations_tenant_id_fkey");
                });

            modelBuilder.Entity("Application.Customers.Postgres.CustomerProgramRow", b =>
                {
                    b.HasOne("Application.Customers.Postgres.CustomerAccountReferenceRow", null)
                        .WithMany()
                        .HasForeignKey("CreatedByAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("programs_created_by_account_id_fkey");

                    b.HasOne("Application.Customers.Postgres.CustomerOrganizationRow", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_customer_programs_organization");
                });

            modelBuilder.Entity("Application.Customers.Postgres.OrganizationReceiptRow", b =>
                {
                    b.HasOne("Application.Customers.Postgres.CustomerAccountReferenceRow", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("organization_receipts_account_id_fkey");

                    b.HasOne("Application.Customers.Postgres.CustomerOrganizationRow", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_customer_organization_receipts_organization");
                });

            modelBuilder.Entity("Application.Customers.Postgres.ProgramReceiptRow", b =>
                {
                    b.HasOne("Application.Customers.Postgres.CustomerAccountReferenceRow", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("program_receipts_account_id_fkey");

                    b.HasOne("Application.Customers.Postgres.CustomerProgramRow", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ProgramId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_customer_program_receipts_program");
                });
            modelBuilder.Entity("Application.Customers.Postgres.CustomerIndividualRow", b =>
                {
                    b.Property<Guid>("TenantId").HasColumnType("uuid").HasColumnName("tenant_id");
                    b.Property<Guid>("Id").HasColumnType("uuid").HasColumnName("id");
                    b.Property<string>("DisplayName").IsRequired().HasMaxLength(200)
                        .HasColumnType("character varying(200)").HasColumnName("display_name");
                    b.Property<string>("Email").HasMaxLength(254)
                        .HasColumnType("character varying(254)").HasColumnName("email");
                    b.Property<string>("Phone").HasMaxLength(32)
                        .HasColumnType("character varying(32)").HasColumnName("phone");
                    b.Property<int>("Availability").HasColumnType("integer").HasColumnName("availability");
                    b.Property<long>("Revision").HasColumnType("bigint").HasColumnName("revision");
                    b.Property<Guid>("CreatedByAccountId").HasColumnType("uuid")
                        .HasColumnName("created_by_account_id");
                    b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");
                    b.Property<Guid?>("AvailabilityChangedByAccountId").HasColumnType("uuid")
                        .HasColumnName("availability_changed_by_account_id");
                    b.Property<DateTimeOffset?>("AvailabilityChangedAt")
                        .HasColumnType("timestamp with time zone").HasColumnName("availability_changed_at");
                    b.HasKey("TenantId", "Id").HasName("pk_customer_individuals");
                    b.HasIndex("Id").IsUnique().HasDatabaseName("ux_customer_individuals_id");
                    b.HasIndex("CreatedByAccountId");
                    b.HasIndex("AvailabilityChangedByAccountId");
                    b.ToTable("individuals", "customers", t =>
                        {
                            t.HasCheckConstraint("ck_customer_individuals_name", "btrim(display_name) <> ''");
                            t.HasCheckConstraint("ck_customer_individuals_email", "email IS NULL OR btrim(email) <> ''");
                            t.HasCheckConstraint("ck_customer_individuals_phone", "phone IS NULL OR btrim(phone) <> ''");
                            t.HasCheckConstraint("ck_customer_individuals_availability", "availability IN (1, 2)");
                            t.HasCheckConstraint("ck_customer_individuals_revision", "revision > 0");
                            t.HasCheckConstraint("ck_customer_individuals_change_pair",
                                "(availability_changed_by_account_id IS NULL) = (availability_changed_at IS NULL)");
                        });
                });

            modelBuilder.Entity("Application.Customers.Postgres.CustomerIndividualCommandReceiptRow", b =>
                {
                    b.Property<Guid>("TenantId").HasColumnType("uuid").HasColumnName("tenant_id");
                    b.Property<Guid>("AccountId").HasColumnType("uuid").HasColumnName("account_id");
                    b.Property<string>("Operation").IsRequired().HasMaxLength(16)
                        .HasColumnType("character varying(16)").HasColumnName("operation");
                    b.Property<string>("IdempotencyKey").IsRequired().HasMaxLength(128)
                        .HasColumnType("character varying(128)").HasColumnName("idempotency_key");
                    b.Property<string>("Fingerprint").IsRequired().HasMaxLength(64)
                        .HasColumnType("character(64)").HasColumnName("fingerprint").IsFixedLength();
                    b.Property<Guid>("IndividualId").HasColumnType("uuid").HasColumnName("individual_id");
                    b.Property<string>("DisplayName").IsRequired().HasMaxLength(200)
                        .HasColumnType("character varying(200)").HasColumnName("display_name");
                    b.Property<string>("Email").HasMaxLength(254)
                        .HasColumnType("character varying(254)").HasColumnName("email");
                    b.Property<string>("Phone").HasMaxLength(32)
                        .HasColumnType("character varying(32)").HasColumnName("phone");
                    b.Property<int>("Availability").HasColumnType("integer").HasColumnName("availability");
                    b.Property<long>("Revision").HasColumnType("bigint").HasColumnName("revision");
                    b.Property<Guid>("CreatedByAccountId").HasColumnType("uuid")
                        .HasColumnName("created_by_account_id");
                    b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");
                    b.Property<Guid?>("AvailabilityChangedByAccountId").HasColumnType("uuid")
                        .HasColumnName("availability_changed_by_account_id");
                    b.Property<DateTimeOffset?>("AvailabilityChangedAt")
                        .HasColumnType("timestamp with time zone").HasColumnName("availability_changed_at");
                    b.HasKey("TenantId", "AccountId", "Operation", "IdempotencyKey")
                        .HasName("pk_customer_individual_command_receipts");
                    b.HasIndex("AccountId");
                    b.HasIndex("TenantId", "IndividualId")
                        .HasDatabaseName("ix_customer_individual_receipts_individual");
                    b.ToTable("individual_command_receipts", "customers", t =>
                        {
                            t.HasCheckConstraint("ck_customer_individual_receipts_operation", "operation IN ('create', 'availability')");
                            t.HasCheckConstraint("ck_customer_individual_receipts_key", "btrim(idempotency_key) <> ''");
                            t.HasCheckConstraint("ck_customer_individual_receipts_fingerprint", "fingerprint ~ '^[0-9a-f]{64}$'");
                            t.HasCheckConstraint("ck_customer_individual_receipts_name", "btrim(display_name) <> ''");
                            t.HasCheckConstraint("ck_customer_individual_receipts_availability", "availability IN (1, 2)");
                            t.HasCheckConstraint("ck_customer_individual_receipts_revision", "revision > 0");
                            t.HasCheckConstraint("ck_customer_individual_receipts_change_pair",
                                "(availability_changed_by_account_id IS NULL) = (availability_changed_at IS NULL)");
                        });
                });

            modelBuilder.Entity("Application.Customers.Postgres.CustomerIndividualRow", b =>
                {
                    b.HasOne("Application.Customers.Postgres.CustomerTenantReferenceRow", null)
                        .WithMany().HasForeignKey("TenantId").OnDelete(DeleteBehavior.Restrict)
                        .IsRequired().HasConstraintName("individuals_tenant_id_fkey");
                    b.HasOne("Application.Customers.Postgres.CustomerAccountReferenceRow", null)
                        .WithMany().HasForeignKey("CreatedByAccountId").OnDelete(DeleteBehavior.Restrict)
                        .IsRequired().HasConstraintName("individuals_created_by_account_id_fkey");
                    b.HasOne("Application.Customers.Postgres.CustomerAccountReferenceRow", null)
                        .WithMany().HasForeignKey("AvailabilityChangedByAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("individuals_availability_changed_by_account_id_fkey");
                });

            modelBuilder.Entity("Application.Customers.Postgres.CustomerIndividualCommandReceiptRow", b =>
                {
                    b.HasOne("Application.Customers.Postgres.CustomerAccountReferenceRow", null)
                        .WithMany().HasForeignKey("AccountId").OnDelete(DeleteBehavior.Restrict)
                        .IsRequired().HasConstraintName("individual_receipts_account_id_fkey");
                    b.HasOne("Application.Customers.Postgres.CustomerIndividualRow", null)
                        .WithMany().HasForeignKey("TenantId", "IndividualId")
                        .OnDelete(DeleteBehavior.Restrict).IsRequired()
                        .HasConstraintName("fk_customer_individual_receipts_individual");
                });
#pragma warning restore 612, 618
        }
    }
}
