// <auto-generated />
using System;
using Application.Customers.Postgres;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Application.Customers.Postgres.Migrations
{
    [DbContext(typeof(CustomerDbContext))]
    partial class CustomerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("customers")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Application.Customers.Postgres.CustomerAccountReferenceRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.HasKey("Id");

                    b.ToTable("accounts", "identity_access", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Application.Customers.Postgres.CustomerOrganizationRow", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_account_id");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.HasKey("TenantId", "Id")
                        .HasName("pk_customer_organizations");

                    b.HasIndex("CreatedByAccountId");

                    b.HasIndex("Id")
                        .IsUnique()
                        .HasDatabaseName("ux_customer_organizations_id");

                    b.HasIndex("TenantId", "CreatedAt", "Id")
                        .IsDescending(false, true, true)
                        .HasDatabaseName("ix_customer_organizations_browse");

                    b.ToTable("organizations", "customers", t =>
                        {
                            t.HasCheckConstraint("ck_customer_organizations_name", "btrim(display_name) <> ''");
                        });
                });

            modelBuilder.Entity("Application.Customers.Postgres.CustomerProgramRow", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_account_id");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.HasKey("TenantId", "Id")
                        .HasName("pk_customer_programs");

                    b.HasIndex("CreatedByAccountId");

                    b.HasIndex("Id")
                        .IsUnique()
                        .HasDatabaseName("ux_customer_programs_id");

                    b.HasIndex("TenantId", "OrganizationId", "Id")
                        .IsUnique()
                        .HasDatabaseName("ux_customer_programs_organization_identity");

                    b.HasIndex("TenantId", "OrganizationId", "CreatedAt", "Id")
                        .IsDescending(false, false, true, true)
                        .HasDatabaseName("ix_customer_programs_browse");

                    b.ToTable("programs", "customers", t =>
                        {
                            t.HasCheckConstraint("ck_customer_programs_name", "btrim(display_name) <> ''");
                        });
                });

            modelBuilder.Entity("Application.Customers.Postgres.CustomerTenantReferenceRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.HasKey("Id");

                    b.ToTable("tenants", "tenancy", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Application.Customers.Postgres.OrganizationReceiptRow", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("idempotency_key");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("fingerprint")
                        .IsFixedLength();

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.HasKey("TenantId", "AccountId", "IdempotencyKey")
                        .HasName("pk_customer_organization_receipts");

                    b.HasIndex("AccountId");

                    b.HasIndex("TenantId", "OrganizationId")
                        .HasDatabaseName("ix_customer_organization_receipts_organization");

                    b.ToTable("organization_receipts", "customers", t =>
                        {
                            t.HasCheckConstraint("ck_customer_organization_receipts_fingerprint", "fingerprint ~ '^[0-9a-f]{64}$'");

                            t.HasCheckConstraint("ck_customer_organization_receipts_key", "btrim(idempotency_key) <> ''");
                        });
                });

            modelBuilder.Entity("Application.Customers.Postgres.ProgramReceiptRow", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("idempotency_key");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("fingerprint")
                        .IsFixedLength();

                    b.Property<Guid>("ProgramId")
                        .HasColumnType("uuid")
                        .HasColumnName("program_id");

                    b.HasKey("TenantId", "AccountId", "IdempotencyKey")
                        .HasName("pk_customer_program_receipts");

                    b.HasIndex("AccountId");

                    b.HasIndex("TenantId", "ProgramId")
                        .HasDatabaseName("ix_customer_program_receipts_program");

                    b.ToTable("program_receipts", "customers", t =>
                        {
                            t.HasCheckConstraint("ck_customer_program_receipts_fingerprint", "fingerprint ~ '^[0-9a-f]{64}$'");

                            t.HasCheckConstraint("ck_customer_program_receipts_key", "btrim(idempotency_key) <> ''");
                        });
                });

            modelBuilder.Entity("Application.Customers.Postgres.CustomerOrganizationRow", b =>
                {
                    b.HasOne("Application.Customers.Postgres.CustomerAccountReferenceRow", null)
                        .WithMany()
                        .HasForeignKey("CreatedByAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("organizations_created_by_account_id_fkey");

                    b.HasOne("Application.Customers.Postgres.CustomerTenantReferenceRow", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("organizations_tenant_id_fkey");
                });

            modelBuilder.Entity("Application.Customers.Postgres.CustomerProgramRow", b =>
                {
                    b.HasOne("Application.Customers.Postgres.CustomerAccountReferenceRow", null)
                        .WithMany()
                        .HasForeignKey("CreatedByAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("programs_created_by_account_id_fkey");

                    b.HasOne("Application.Customers.Postgres.CustomerOrganizationRow", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_customer_programs_organization");
                });

            modelBuilder.Entity("Application.Customers.Postgres.OrganizationReceiptRow", b =>
                {
                    b.HasOne("Application.Customers.Postgres.CustomerAccountReferenceRow", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("organization_receipts_account_id_fkey");

                    b.HasOne("Application.Customers.Postgres.CustomerOrganizationRow", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_customer_organization_receipts_organization");
                });

            modelBuilder.Entity("Application.Customers.Postgres.ProgramReceiptRow", b =>
                {
                    b.HasOne("Application.Customers.Postgres.CustomerAccountReferenceRow", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("program_receipts_account_id_fkey");

                    b.HasOne("Application.Customers.Postgres.CustomerProgramRow", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ProgramId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_customer_program_receipts_program");
                });
#pragma warning restore 612, 618
        }
    }
}
