<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../foundation/application-kernel/SquiFlow.ApplicationKernel/SquiFlow.ApplicationKernel.csproj" />
    <ProjectReference Include="../../modules/customers/SquiFlow.Customers/SquiFlow.Customers.csproj" />
    <ProjectReference Include="../../apps/desktop/guard/SquiFlow.Guard/SquiFlow.Guard.csproj" />
  </ItemGroup>
</Project>
